# codecov.yml
# Codecov configuration file
# See https://docs.codecov.com/docs/codecov-yaml for details

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

ignore:
  - 'setup.py'
  - '**/setup.py'
  - 'cobyqa/_build_utils/*.py'
  - 'cobyqa/utils/_min_dependencies.py'
  - 'cobyqa/utils/_show_versions.py'
  - '**/tests/*.py'

comment: false

github_checks:
    annotations: false