# codecov.yml
# Codecov configuration file
# See https://docs.codecov.com/docs/codecov-yaml for details

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

ignore:
  - 'setup.py'
  - '**/setup.py'
  - 'cobyqa/_min_dependencies.py'

comment: false

github_checks:
    annotations: false