# Codecov configuration file

coverage:
  status:
    project:
      default:
        target: 1
      patch:
        target: 0  # some PRs might affect uncovered code only

github_checks:
  annotations: false

ignore:
  - '**/tests/*.py'
  - 'cobyqa/utils/versions.py'
