# codecov.yml
# Codecov configuration file
# See https://docs.codecov.com/docs/codecov-yaml for details

codecov:
  require_ci_to_pass: no
  notify:
    require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: 1
    patch:
      default:
        target: 0
        if_ci_failed: error

ignore:
  - 'setup.py'
  - '**/setup.py'
  - 'cobyqa/_build_utils/*.py'
  - 'cobyqa/utils/_min_dependencies.py'
  - 'cobyqa/utils/_show_versions.py'
  - '**/tests/*.py'

comment: false
