[build-system]
requires = [
    "setuptools",
    "wheel",
    "oldest-supported-numpy",
    "scipy>=1.1.0",
    "Cython>=0.29.23",
]

[tool.pytest.ini_options]
addopts = "-v -ra -l --strict-markers"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.cibuildwheel]
archs = "all"
build-verbosity = "3"
test-command = "bash {project}/build_tools/github/test_wheels.sh"

[tool.cibuildwheel.macos]
test-skip = "*_arm64 *_universal2:arm64"
