[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython>=0.29.23",
    "oldest-supported-numpy",
]

[tool.pytest.ini_options]
addopts = "-v -ra -l --color=yes --code-highlight=yes --strict-markers"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]