name: Bug Report

description: Report a bug.

labels: ['Bug: triage']

body:
  - type: markdown
    attributes:
      value: >
        Thank you for submitting a bug report.
        Before creating a new issue, please make sure to check the
        [issue tracker](https://github.com/ragonneau/cobyqa/issues)
        for existing issues about the bug.
  - type: textarea
    attributes:
      label: Describe the bug
      description: >
        A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/Code to Reproduce
      description: |
        Please add a minimal example that to reproduce the error.
      placeholder: |
        ```
        import cobyqa
        << your code here >>
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        Please describe the expected results.
      placeholder: >
        Example: No error is raised.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        Please describe the results you observe.
      placeholder: >
        Please describe the actual output or **full** traceback.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Versions
      description: |
        Please run the following and paste the output below.
        ```
        import sys, cobyqa; print(cobyqa.__version__, sys.version)
        ```
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thank you for your contribution!