name: Bug Report
description: Report a bug.
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report.
        Before creating a new issue, please make sure to check the [issue tracker](https://github.com/ragonneau/cobyqa/issues) for existing issues about the bug.
  - type: textarea
    attributes:
      label: Bug description
      description: |
        Please provide a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug reproduction
      description: |
        Please add a minimal example that reproduces the error.
      placeholder: |
        ```
        << Sample code to reproduce the problem >>
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Results
      description: |
        Please describe the results you expect.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: |
        Please describe the results you observe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Versions
      description: |
        Please run the following and paste the output below.
        ```python
        import sys, cobyqa; print(cobyqa.__version__, sys.version)
        ```
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution!