# .github/ISSUE_TEMPLATE/feature_request.yml
# Feature request issue form

name: Feature request
description: Request a new feature.
labels: ['enhancement']

body:
  - type: textarea
    attributes:
      label: Feature description
      description: >
        Describe the feature you want to enable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        Describe your proposed solution.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Considered alternatives
      description: >
        Describe the alternatives you have considered.
    validations:
      required: false
