name: Feature request
description: Request a new feature.
labels: ['enhancement']

body:
  - type: textarea
    attributes:
      label: Describe the feature you want to enable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe your proposed solution.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you have considered.
    validations:
      required: false