name: Feature request
description: Request a new feature.
labels: ['enhancement']

body:
  - type: textarea
    attributes:
      label: Feature description
      value: |
        Describe the feature you want to enable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Proposed solution
      value: |
        Describe your proposed solution.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Considered alternatives
      value: |
        Describe the alternatives you have considered.
    validations:
      required: false