# .github/workflows/coverage.yml
# Codecov configuration file
# See https://github.com/codecov/codecov-action for details

name: codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Generate coverage report for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate coverage reports
        run: bash build_tools/github/generate_coverage.sh

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
