name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    name: Upload coverage report for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Generate coverage report
        run: bash build_tools/github/coverage.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
