# Compare the current version of the package with the latest version on PyPI.

name: compare

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_package:
    name: Compare current version with latest version on PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Rename the package
        run: bash .github/actions/compare/rename.sh

      - name: Install CUTEst and its dependencies
        run: bash .github/actions/compare/install-cutest.sh
