# .github/workflows/coverage.yml
# GitHub Actions configuration file for Codecov
# See https://github.com/codecov/codecov-action for details

name: Coverage reports

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    name: Coverage report for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
    steps:
      - name: Checkout cobyqa
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate coverage report
        run: bash build_tools/github/coverage.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
