# Python code linting

name: lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  flake8-lint:
    name: Lint using flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install flake8

      - name: Lint with flake8
        run: flake8 . > flake8.txt

      - name: Comment on commit
        uses: peter-evans/commit-comment@v3
        with:
          body-path: flake8.txt
