# .github/workflows/wheels.yml
# GitHub Actions configuration file for building wheels
# See https://github.com/pypa/cibuildwheel for details

name: wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit Windows
          - os: windows-latest
            python: 37
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 38
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 39
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 310
            bitness: 64
            platform_id: win_amd64

          # 32-bit Windows
          - os: windows-latest
            python: 37
            bitness: 32
            platform_id: win32
          - os: windows-latest
            python: 38
            bitness: 32
            platform_id: win32
          - os: windows-latest
            python: 39
            bitness: 32
            platform_id: win32

          # 64-bit Linux manylinux2010
          - os: ubuntu-latest
            python: 37
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010

          # 32-bit Linux manylinux2010
          - os: ubuntu-latest
            python: 37
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 38
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 39
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010

          # 64-bit Linux manylinux2014 x86_64
          - os: ubuntu-latest
            python: 37
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: 310
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # 64-bit Linux manylinux2014 aarch64
          - os: self-hosted
            python: 37
            bitness: 64
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: self-hosted
            python: 38
            bitness: 64
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: self-hosted
            python: 39
            bitness: 64
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014
          - os: self-hosted
            python: 310
            bitness: 64
            platform_id: manylinux_aarch64
            manylinux_image: manylinux2014

          # macOS x86_64
          - os: macos-latest
            bitness: 64
            python: 37
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 38
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 39
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          # macOS arm64
          - os: macos-latest
            bitness: 64
            python: 38
            platform_id: macosx_arm64
          - os: macos-latest
            bitness: 64
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        if: ${{ runner.arch == 'X86' || runner.arch == 'X64' }}
        uses: actions/setup-python@v2

      - name: Build wheels
        run: bash build_tools/github/build_wheels.sh
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_ENVIRONMENT: PIP_DEFAULT_TIMEOUT=21600
          CIBW_TEST_SKIP: "{*-*linux_{aarch64,ppc64le,s390x},*-macosx_arm64}"
          CIBW_TEST_COMMAND: bash {project}/build_tools/github/test_wheels.sh
          CIBW_BUILD_VERBOSITY: 1

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build source distribution
        run: bash build_tools/github/build_source.sh

      - name: Test source distribution
        run: bash build_tools/github/test_source.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build_wheels, build_sdist]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Upload artifacts to Anaconda
        run: bash build_tools/github/upload_anaconda.sh
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
