# .github/workflows/wheels.yml
# GitHub Actions configuration file for building wheels
# See https://github.com/pypa/cibuildwheel for details

name: Build wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheel distribution for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows 64-bit versions
          - os: windows-latest
            python: 36
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 37
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 38
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 39
            bitness: 64
            platform_id: win_amd64
          - os: windows-latest
            python: 310
            bitness: 64
            platform_id: win_amd64

          # Windows 32-bit versions
          # NumPy is not yet compiled for Python 3.10
          - os: windows-latest
            python: 36
            bitness: 32
            platform_id: win32
          - os: windows-latest
            python: 37
            bitness: 32
            platform_id: win32
          - os: windows-latest
            python: 38
            bitness: 32
            platform_id: win32
          - os: windows-latest
            python: 39
            bitness: 32
            platform_id: win32

          # Linux 64-bit versions using manylinux1
          # NumPy is not compiled for Python 3.10
          - os: ubuntu-latest
            python: 36
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux1
          - os: ubuntu-latest
            python: 37
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux1
          - os: ubuntu-latest
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux1
          - os: ubuntu-latest
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux1

          # Linux 32-bit versions using manylinux1
          # NumPy is not compiled for Python 3.10
          - os: ubuntu-latest
            python: 36
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux1
          - os: ubuntu-latest
            python: 37
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux1
          - os: ubuntu-latest
            python: 38
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux1
          - os: ubuntu-latest
            python: 39
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux1

          # Linux 64-bit versions using manylinux2010
          # NumPy is not compiled for Python 3.10
          - os: ubuntu-latest
            python: 36
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 37
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 38
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 39
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2010

          # Linux 32-bit versions using manylinux2010
          # NumPy is not compiled for Python 3.10
          - os: ubuntu-latest
            python: 36
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 37
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 38
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010
          - os: ubuntu-latest
            python: 39
            bitness: 32
            platform_id: manylinux_i686
            manylinux_image: manylinux2010

          # Linux 64-bit versions using manylinux2014
          # NumPy for Python 3.10 is only available with manylinux2014
          - os: ubuntu-latest
            python: 310
            bitness: 64
            platform_id: manylinux_x86_64
            manylinux_image: manylinux2014

          # macOS 64-bit versions
          - os: macos-latest
            bitness: 64
            python: 36
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 37
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 38
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 39
            platform_id: macosx_x86_64
          - os: macos-latest
            bitness: 64
            python: 310
            platform_id: macosx_x86_64

          # macOS arm64
          # NumPy is not compiled for Python >= 3.8
          - os: macos-latest
            bitness: 64
            python: 38
            platform_id: macosx_arm64
          - os: macos-latest
            bitness: 64
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest
            bitness: 64
            python: 310
            platform_id: macosx_arm64

    steps:
      - name: Checkout cobyqa
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build and test wheel distributions
        run: bash build_tools/github/build_wheels.sh
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
          CIBW_ARCHS: all
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_TEST_SKIP: "*-macosx_arm64"
          # TODO: CIBW_REPAIR_WHEEL_COMMAND_WINDOWS
          # TODO: CIBW_BEFORE_TEST_WINDOWS
          CIBW_TEST_COMMAND: bash {project}/build_tools/github/test_wheels.sh
          # TODO: CIBW_TEST_COMMAND_WINDOWS
          CIBW_BUILD_VERBOSITY: 1

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cobyqa
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build source distribution
        run: bash build_tools/github/build_source.sh

      - name: Test source distribution
        run: bash build_tools/github/test_source.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build_wheels, build_sdist]

    steps:
      - name: Checkout cobyqa
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Upload artifacts to Anaconda
        run: bash build_tools/github/upload_anaconda.sh
        env:
          ANACONDA_ORG: ragonneau
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
